#!/bin/bash

# Config file
if [ -n "$1" ] && [ -r "$1" ]; then
	EASY_FLAMEGRAPH_DEFAULT="$1"
else
	EASY_FLAMEGRAPH_DEFAULT=/etc/default/easy-flamegraph.conf
fi

[ -r "$EASY_FLAMEGRAPH_DEFAULT" ] && . "$EASY_FLAMEGRAPH_DEFAULT"

if ! $USE_EASY_FLAMEGRAPH; then
	exit 0
fi

# source lib
[ -r "$EASY_FLAME_LIB_DIR"/lib ] && . "$EASY_FLAME_LIB_DIR"/lib

# run all scripts in conditions dir
DATE_SYS=$(date '+%Y.%m.%d-%H.%M.%S')
DATE_UTC=$(date -u '+%Y.%m.%d-%H.%M.%S')
debug_log "-------------------------------------------------------"
debug_log "Start time:"
debug_log "System: $DATE_SYS"
debug_log "UTC: $DATE_UTC"

# check if the required tool(s) is installed. e.g. linux-tools-common.
required_tools_checking linux-tools-common
required_tools_checking linux-tools-"$(uname -r)"
required_tools_checking binutils
required_tools_checking zip
required_tools_checking sysstat

# check configurations
# -t is to tar the intermediate files which is conflicted with the --keep-svg
# which keeps only the .svg file
if "$G_KEEP_SVG" && "$G_KEEP_TAR"; then
	echo "Cannot set G_KEEP_SVG and G_KEEP_TAR together"
	exit 1
fi

debug_log "Run scripts in $EASY_FLAME_COND_DIR"
for cond_script in "$EASY_FLAME_COND_DIR"/*; do
	if [ -f "$cond_script" ] && [ -x "$cond_script" ]; then
		debug_log "Run $cond_script"
		bash "$cond_script" "$EASY_FLAMEGRAPH_DEFAULT"
	fi
done

exit 0

if $USE_MEM; then
	if [ x"$EASY_FLAME_OUTPUT" != x"" ]; then
		FLAME_MEM_CMD="$FLAME_MEM_CMD -o $EASY_FLAME_OUTPUT/mem"
	fi

	if [ x"$USE_MEM_PID" != x"" ]; then
		FLAME_MEM_CMD="$FLAME_MEM_CMD -p $USE_MEM_PID"
	fi

	if [ x"$USE_MEM_THRESHOLD_SIZE" != x"" ]; then
		FLAME_MEM_CMD="$FLAME_MEM_CMD -s $USE_MEM_THRESHOLD_SIZE"
	fi

	if $USE_MEM_TAR; then
		FLAME_MEM_CMD="$FLAME_MEM_CMD -t"
	fi

	if $USE_MEM_GLIBC; then
		FLAME_MEM_CMD="$FLAME_MEM_CMD --glibc"
	fi

	if $USE_MEM_SVG; then
		FLAME_MEM_CMD="$FLAME_MEM_CMD --keep-svg"
	fi

	if $USE_MEM_KMEM; then
		FLAME_MEM_CMD="$FLAME_MEM_CMD --kmem"
	fi

	if [ x"$USE_MEM_SRATE" != x"" ]; then
		FLAME_MEM_CMD="$FLAME_MEM_CMD --sample-rate $USE_MEM_SRATE"
	fi

	if $USE_MEM_TCMALLOC; then
		FLAME_MEM_CMD="$FLAME_MEM_CMD --tcmalloc"
	fi

	$FLAME_MEM_CMD  &
fi
