#!/bin/bash

path_mem_ftrace="$(realpath $0)/"
dirname_mem_ftrace="$(dirname $path_mem_ftrace)"
dirname_config="${dirname_mem_ftrace%conditions*}"
EASY_FLAMEGRAPH_DEFAULT="${dirname_config}easy-flamegraph.conf"

! [ -r "$EASY_FLAMEGRAPH_DEFAULT" ] && EASY_FLAMEGRAPH_DEFAULT="/etc/default/easy-flamegraph.conf"

# Overwrite the default config
if [ -n "$1" ] && [ -r "$1" ]; then
	EASY_FLAMEGRAPH_DEFAULT="$1"
else
	if ! [ -r "$EASY_FLAMEGRAPH_DEFAULT" ]; then
		echo "Unable to read config file $1"
		exit 1
	fi
fi

echo "Use $EASY_FLAMEGRAPH_DEFAULT as the config file"

[ -r "$EASY_FLAMEGRAPH_DEFAULT" ] && . "$EASY_FLAMEGRAPH_DEFAULT"

# source lib
[ -r "$EASY_FLAME_LIB_DIR"/lib ] && . "$EASY_FLAME_LIB_DIR"/lib

prepare_to_gen_flamegraph() {
	# TODO: need to implement the mem threshold checking
	local anon=""
	local file=""
	# The memory ftrace is captured after 5s with executing date command
	local subtitle="${DATE}+5s"
	local title="Mem Allocation Flamegraph"
	local type="--ftrace"
	local uname=""
	local per_cpu_flame="false"

	# TODO: need to implement the per-cpu flamegraph
	if $G_PER_CPU_FLAMEGRAPH; then
		debug_log "${FUNCNAME[0]}: The per-cpu flamegraph for ftrace is not implemented!!"
	fi

	if "$G_KEEP_SVG"; then
		KEEP_SVG_OPTION="-d"
	elif "$G_KEEP_TAR"; then
		KEEP_SVG_OPTION="-t"
	else
		KEEP_SVG_OPTION=""
	fi

	anon=$(awk '/anon/{sum+=$2} END {print "anon:" sum/1048576 "GB"}' /proc/meminfo)
	file=$(awk '/file/{sum+=$2} END {print "file:" sum/1048576 "GB"}' /proc/meminfo)
	subtitle="${subtitle} $(grep -Pi '((mem|swap)(free|total)|reclaimable)' /proc/meminfo)"
	subtitle="${subtitle} ${file} ${anon}"
	debug_log "CMD: "$EASY_FLAME_LIB_DIR"/gen-flamegraph.sh -i "$data_path" "$KEEP_SVG_OPTION""
	debug_log "-o "$output_dir" --title $title --subtitle $subtitle "
	debug_log "-p "$per_cpu_flame" "$type" --mem-flame '>>' "$EASY_FLAME_LOG""

	# Redirect the output message to both console and easy-flamegraph log file
	"$EASY_FLAME_LIB_DIR"/gen-flamegraph.sh -i "$data_path" "$KEEP_SVG_OPTION" \
		-o "$output_dir" --title "$title" --subtitle "$subtitle" \
		-p "$per_cpu_flame" "$type" --mem-flame 2>&1 | tee -a "$EASY_FLAME_LOG"
}

restore_sym_addr=false
restore_sym_offset=false

# create output directory for different type
output_dir="$EASY_FLAME_OUTPUT"/mem
mkdir -p "$output_dir"
DATE=$(date +%Y-%m-%d_%H%M%S)
ext="memtrace"

# data location
data_path="${output_dir}/${DATE}.mem.${ext}"

debug_log "USE_MEM_FTRACE: enabled"

debug_log "set nop as the default tracer"
echo function_graph > /sys/kernel/debug/tracing/current_tracer
# echo function_graph > /sys/kernel/debug/tracing/current_tracer

debug_log "Clear the filter!"
echo > /sys/kernel/debug/tracing/set_ftrace_filter

debug_log "Clear the set_graph_function"
#echo __alloc_pages_nodemask > /sys/kernel/debug/tracing/set_graph_function
echo __alloc_pages_nodemask > /sys/kernel/debug/tracing/set_ftrace_filter

debug_log "Clear the trace buffer!"
echo > /sys/kernel/debug/tracing/trace

debug_log "Insert kmem__alloc_pages_nodemask trace point!"
if grep -q kmem__alloc_pages_nodemask /sys/kernel/debug/tracing/kprobe_events; then
	# debug_log "Remove the the existing blk_mq_start_request trace event!"
	echo "Remove the the existing kmem__alloc_pages_nodemask trace event!"
	echo '-:kmem__alloc_pages_nodemask' >> /sys/kernel/debug/tracing/kprobe_events
fi

debug_log "Insert again kmem__alloc_pages_nodemask trace event!"
echo 'p:kmem__alloc_pages_nodemask __alloc_pages_nodemask request=%di' >> /sys/kernel/debug/tracing/kprobe_events

debug_log "Insert kmem:mm_page_alloc trace event!"
echo 'kmem:mm_page_alloc' >> /sys/kernel/debug/tracing/set_event


if ! grep -q "sym\-addr" /sys/kernel/debug/tracing/trace_options; then
	debug_log "set restore_nosym-addr"
	restore_sym_addr=true
	echo "sym-addr" > /sys/kernel/debug/tracing/trace_options
fi

if ! grep -q "sym\-offset" /sys/kernel/debug/tracing/trace_options; then
	debug_log "set restore_nosym-offset"
	restore_sym_offset=true
	echo "sym-offset" > /sys/kernel/debug/tracing/trace_options
fi

echo stacktrace > /sys/kernel/debug/tracing/events/kmem/mm_page_alloc/trigger
echo 1 > /sys/kernel/debug/tracing/events/kprobes/kmem__alloc_pages_nodemask/enable

debug_log "start the tracing"
echo 1 > /sys/kernel/debug/tracing/tracing_on

debug_log "sleep 5 seconds"
echo "The memory allocation sampling will profile 5s....."

sleep 5

echo "done."
debug_log "stop the tracing"
echo 0 > /sys/kernel/debug/tracing/tracing_on

echo 0 > /sys/kernel/debug/tracing/events/kprobes/kmem__alloc_pages_nodemask/enable

debug_log "cat the trace result to $data_path"
# generate the trace log by cpu order instead of cating the default trace file
# to avoid the log messing up(i.e. cat /sys/kernel/debug/tracing/trace >
# "$data_path"). And the messing up would make the stackcollapse script parse
# wrong.
for i in $(ls /sys/kernel/debug/tracing/per_cpu/); do
	# echo $i;
	# echo ----;
	cat /sys/kernel/debug/tracing/per_cpu/$i/trace >> "$data_path"
	# echo ----
done

prepare_to_gen_flamegraph

# Remember to remove the event after cating the trace log, or the trace log
# cannot find the event probe points and will output the unknow type:
#           <...>-2613639 [003] ...2 956467.930520: Unknown type 2286
#  irq/47-ahci[000-251   [000] ..s2 956467.932550: Unknown type 2287
#      jbd2/sda1-8-282   [001] ...2 956467.932655: Unknown type 2286
#  irq/47-ahci[000-251   [000] ..s2 956467.932979: Unknown type 2287
#            <...>-264029 [001] ...2 956467.933010: Unknown type 2286
#            <...>-749159 [000] ...2 956467.976818: Unknown type 2286
#  irq/47-ahci[000-251   [000] ..s2 956467.976939: Unknown type 2287
#            <...>-749159 [000] ...2 956467.976945: Unknown type 2286
echo '!kmem:mm_page_alloc' >> /sys/kernel/debug/tracing/set_event

echo '!stacktrace' > /sys/kernel/debug/tracing/events/kmem/mm_page_alloc/trigger
echo '-:kmem__alloc_pages_nodemask' >> /sys/kernel/debug/tracing/kprobe_events

if $restore_sym_offset; then
	debug_log "restore nosym-offset"
	echo nosym-offset > /sys/kernel/debug/tracing/trace_options
fi

if $restore_sym_addr; then
	debug_log "restore nosym-addr"
	echo nosym-addr > /sys/kernel/debug/tracing/trace_options
fi

debug_log "Clear the trace buffer!"
echo > /sys/kernel/debug/tracing/trace
