Document: easy-flamegraph
Title: Debian easy-flamegraph Manual
Author: <insert document author here>
Abstract: This manual describes what easy-flamegraph is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/easy-flamegraph/easy-flamegraph.sgml.gz

Format: postscript
Files: /usr/share/doc/easy-flamegraph/easy-flamegraph.ps.gz

Format: text
Files: /usr/share/doc/easy-flamegraph/easy-flamegraph.text.gz

Format: HTML
Index: /usr/share/doc/easy-flamegraph/html/index.html
Files: /usr/share/doc/easy-flamegraph/html/*.html
